### ISSUE TITLE
Add featured speakers from eventyay to start page.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2019.fossasia.org#106]
Eventyay has a featured speakers list. Please add the missing speakers to the start page: https://eventyay.com/e/3689bc98/

![screenshot from 2019-03-07 13-00-30](https://user-images.githubusercontent.com/1583873/53933371-05267c80-40d9-11e9-8227-7fa0b8cb11fa.png)

**Comment by kushthedude** [comment]
@mariobehling 
Sir,I would like to work on it

**Comment by dcjc29** [comment]
@mariobehling 
Sir,can I work on this issue?I would like to resolve this issue.Thank you

**Comment by kushthedude** [comment]
I am already on it.

**Comment by mohitm15** [comment]
@mariobehling 
Sir, ,I want to take this issue

**Comment by mariobehling** [comment]
Thanks, this is done already in the first step.
