### ISSUE TITLE
Title is too long  in index.html

### ISSUE THREAD

**Issue by snitin315** [fossasia/2019.fossasia.org#134]
**Actual Behaviour**
the title tag in index.html is too long and hence the whole title is not visible in browser tab.
![Screenshot from 2019-10-31 16-59-48](https://user-images.githubusercontent.com/46647141/67943669-88648780-fc00-11e9-89aa-1941b9ca5934.png)

**Expected Behaviour**
The Title tag should contain only FOSSASIA SUMMIT 2019  and the rest of the content is should be present in description meta tag.

**Steps to reproduce it**
open the index.html file and see the <title> tag

**Would you like to work on the issue?**
Yes I would like to work on this issue

**Comment by Palak3103** [comment]
Yes I would like to work on this issue

**Comment by ABHIJITBURMAN** [comment]
i am new in open source. may i work on this projects!!

**Comment by snitin315** [comment]
Not a Priority , Hence closing.
