### ISSUE TITLE
Two lines are overlapping eachother , and these lines are the main highlight of the submit . 

### ISSUE THREAD

**Issue by prashantbarge22** [fossasia/2019.fossasia.org#165]
![Screenshot_2020-05-24-11-27-56-997_com android chrome](https://user-images.githubusercontent.com/64685425/82746880-1d53eb80-9db2-11ea-87e0-6f32e9c265d5.jpg)
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by prashantbarge22** [comment]
There is no space between the two lines between open submit and Singapore these two words are overlapping eachother .

**Comment by divided7** [comment]
I can work on this issue

**Comment by Dhruvibansal** [comment]
I want to work on this issue can I ?Is it still open.

**Comment by prashantbarge22** [comment]
@Dhruvibansal @divided7  I issue is closed. 
Find some other issue . Thank you 
Happy coding .

**Comment by smileynanda99** [comment]
this issue still open can i work on it
