### ISSUE TITLE
Copyright 2020 not perfectly visible

### ISSUE THREAD

**Issue by chetan-v** [fossasia/2019.fossasia.org#169]
**Actual Behaviour**

 In Footer of navbar copyright 2020 not visible completely 

**Expected Behaviour**

 Copyright 2020 should be visible completely 

**Screenshots of the issue**
![Screenshot from 2020-06-11 22-14-51](https://user-images.githubusercontent.com/63091769/84416917-7df87a80-ac32-11ea-9496-b1c8191dc848.png)

**Would you like to work on the issue?**
  yes I want to work on it

**Comment by kunalvirdi** [comment]
I will work on this issue.

**Comment by himanshujaidka** [comment]
Is anyone is working? If yes then let me know please

**Comment by Avinash9k5r** [comment]
I think the issue has been solved.

**Comment by himanshujaidka** [comment]
ok
