### ISSUE TITLE
Create a new CSS style for sub heading on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2019.fossasia.org#49]
The start page has the words "OpenTechSummit Singapore" on the top slider. Please create a new CSS for the subheading and increase the size to 35px. Don't change the existing style which is also used on other parts of the site.

![screenshot from 2018-11-25 19-09-19](https://user-images.githubusercontent.com/1583873/48982662-d0705580-f0e5-11e8-8d33-c60bc63450e5.png)

**Comment by AvaniVerma** [comment]
@mariobehling , may I work on this one if @yash-kedia if not working on it ?
