### ISSUE TITLE
Request to update link for purchasing tickets

### ISSUE THREAD

**Issue by mielamvn** [fossasia/2019.fossasia.org#5]
The ticket tab leads to the link of FOSSASIA Summit 2018.

- [ ] Please replace it with this link: [](https://eventyay.com/e/3689bc98/)

Thank you

**Comment by MadhavBahlMD** [comment]
Hey @mielamvn I can do this, please provide the link.

**Comment by mielamvn** [comment]
Hi, here is the link: https://eventyay.com/e/3689bc98/

Thanks Madhav

**Comment by MadhavBahlMD** [comment]
Replaced the redirect link in tickets/index.html and replaced the links on home page with https://eventyay.com/e/3689bc98/ :+1: 

PR #6 solves this.
