### ISSUE TITLE
Header text on exhibitions page blue on activation: Expected White

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2019.fossasia.org#50]
The header text on the exhibitions page is blue on activation. It should be white.
https://2019.fossasia.org/exhibition/index.html
![screenshot from 2018-11-25 22-10-37](https://user-images.githubusercontent.com/1583873/48984675-1554b600-f0ff-11e8-90ea-aa71f1964344.png)

**Comment by AdityaSrivast** [comment]
@mariobehling Can I work on this issue?

**Comment by Cnd96** [comment]
@mariobehling  Can I work on this issue?
