### ISSUE TITLE
Lines Overlap with Text in Schedule

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/2019.fossasia.org#51]
When the user hovers over some items in the schedule, the text overlaps with the pin and line in the box. There should be extra space between the line and the text to prevent this from happening.

![image](https://user-images.githubusercontent.com/8119928/49199603-bf824700-f366-11e8-8218-651fe2c04e35.png)

**Comment by mohitacecode** [comment]
i will try to resolve it

**Comment by mohitacecode** [comment]
pls provide the link

**Comment by AvaniVerma** [comment]
@Ryan10145 Hey, I'm working on this !!
