### ISSUE TITLE
Ticket information page could also indicate "full" ticket prices

### ISSUE THREAD

**Issue by mjbright** [fossasia/2019.fossasia.org#7]
On the ticket information page there are several "Early Bird" tickets along with their prices.

It would be nice to see the "full" ticket prices which will apply once the "SALES ENDS" date is reached.

**Comment by hpdang** [comment]
@mjbright  thanks for your feedback, how does it look? https://eventyay.com/e/3689bc98/
![screenshot from 2018-08-31 16-54-59](https://user-images.githubusercontent.com/1658742/44919812-a1dd1b80-ad3e-11e8-9456-819b6de1b3a5.png)

**Comment by mjbright** [comment]
Looks great thanks.
