### ISSUE TITLE
Setup Mini-DebConf

### ISSUE THREAD

**Issue by hpdang** [fossasia/2019.fossasia.org#70]
- [ ] Create an eventyay website for Mini-DebConf
- [ ] Update wiki https://wiki.debian.org/DebianEvents/Asia/2019/MiniDebConfSingapore
- [ ] Create a logo similar to https://wiki.debian.org/DebianEvents/fr/2019/Marseille
- [ ] Announce it on Debian Mailing List
- [ ] Announce on social media

**Comment by Dharmesh-Poddar** [comment]
@hpdang  I would like to work on it..
