### ISSUE TITLE
back to top with icon

### ISSUE THREAD

**Issue by mohitacecode** [fossasia/2019.fossasia.org#73]
In the Fossasia website(https://fossasia.org/) the back to top button is given but it is not in the form of icon it is in the left bottom which is not easily visible by the user due to they are not using so we can make this back to top option in the form of an icon

**Comment by amrs-tech** [comment]
I'll try to resolve this issue

**Comment by ebube4im** [comment]
Hi Guys. I am new here and would love to contribute here. Has this issue been closed? There is no back to top yet on the site. Can i take that up?
