### ISSUE TITLE
Add schedule roster as html instead of image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2019.fossasia.org#82]
The schedule roster is an image currently. 

1. Please use the RoomVisual.html file (https://github.com/fossasia/2019.fossasia.org/blob/master/RoomVisual.html) and change the image into html. The requirement is to have the table with cells in the according colors in HTML. No images are needed.
2. Link the tracks to the specific schedule.

![screenshot from 2019-02-20 12-47-53](https://user-images.githubusercontent.com/1583873/53067213-28183480-350e-11e9-8a36-1c2f7bef34ad.png)

**Comment by HarshCic** [comment]
Hey @mariobehling, I want to work on this can you please guide me.

**Comment by mohitm15** [comment]
@mariobehling l am working on it

**Comment by mohitm15** [comment]
@mariobehling  Should I Place a link of the image over the html page??

**Comment by mariobehling** [comment]
The requirement is to have the table with cells in the according colors in HTML. No images are needed.

**Comment by fliptrail** [comment]
@mohitm15 still working or can I take over?

**Comment by mohitm15** [comment]
I am still working on it. 😑

**Comment by fliptrail** [comment]
Just asking cause 5 days have already passed...

**Comment by mohitm15** [comment]
Last 4 days, I was busy in college fest...now l got time to work...😏
You should opt any other issue ☺️

**Comment by mariobehling** [comment]
Anyone who can solve this issue first, please go ahead.

**Comment by mariobehling** [comment]
The file "Roomvisual.html" was updated to the latest version as well. Please refer to the latest version.

**Comment by mohitm15** [comment]
Sir,
So I need to pull the commits in order to update to the newest version.

**Comment by kushthedude** [comment]
@mariobehling Sir,
I have tried to solve the issue
Please review my PR
https://github.com/fossasia/2019.fossasia.org/pull/87
