### ISSUE TITLE
Wrong page title of Exhibition Page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/2019.fossasia.org#94]
**Actual Behaviour**
Page title of Exhibition Page is not appropriate.(See the Year)

**Expected Behaviour**
Page title of Exhibition Page should be correct.

**Steps to reproduce it**
a) Go to 'https://2019.fossasia.org/exhibition/index.html'
b) Check the page title and see the issue.

**Screenshots of the issue**
<img width="1067" alt="screenshot 2019-02-28 at 2 39 57 pm" src="https://user-images.githubusercontent.com/44091822/53555073-3649fe80-3b67-11e9-8a14-d1ab90495817.png">

**Would you like to work on the issue?**
I would be glad to work on this issue.

**Comment by kushthedude** [comment]
@mariobehling ,
Can i work on this small bug?

**Comment by mariobehling** [comment]
There is no bug here. It is perfectly fine the way it is.
